# Generated by Django 4.2.2 on 2023-06-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="prof",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=10)),
                ("email", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("mca", models.CharField(max_length=2550)),
                ("bca", models.CharField(max_length=255)),
                ("twelth", models.CharField(max_length=255)),
                ("tenth", models.CharField(max_length=255)),
                ("lang", models.CharField(max_length=255)),
            ],
        ),
    ]
